using System.Globalization;
using System.Threading;

namespace EngineDjPlaylistSync;

internal static class LocalizationManager
{
    public const string SystemDefaultLanguage = "system";

    private static readonly CultureInfo SystemUiCulture = CultureInfo.CurrentUICulture;

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["Language.System"] = "System default",
        ["Language.English"] = "English",
        ["Language.Spanish"] = "Spanish",
        ["Language.French"] = "French",
        ["Language.German"] = "German",

        ["App.Title"] = "Engine DJ Folder Import Sync",
        ["Button.Browse"] = "Browse...",
        ["Button.Preview"] = "Preview",
        ["Button.MissingFiles"] = "Missing Files",
        ["Button.RefreshPlaylists"] = "Refresh Playlists",
        ["Button.RefreshDrives"] = "Refresh Drives",
        ["Button.DeleteCheckedMissing"] = "Delete Checked Missing Tracks",
        ["Button.LocateCheckedFiles"] = "Locate Checked Files...",
        ["Button.ImportCheckedTracks"] = "Import checked tracks",
        ["Button.Cancel"] = "Cancel",
        ["CheckBox.DarkMode"] = "Dark mode",
        ["CheckBox.Analysis"] = "Generate BPM/waveform analysis for checked tracks",
        ["CheckBox.KeyDetection"] = "Include key detection",
        ["CheckBox.OfficialAnalyzer"] = "Use official Engine DJ OfflineAnalyzer",
        ["CheckBox.OfficialAnalyzerNotFound"] = "Official Engine DJ OfflineAnalyzer not found on this computer",
        ["CheckBox.CaptureOfficialAnalyzer"] = "Save official analyzer capture + decoded waveform payloads",

        ["Label.PrimaryDb"] = "Primary Engine DB (m.db):",
        ["Label.ImportFolder"] = "Import folder:",
        ["Label.UpdateTarget"] = "Update target:",
        ["Label.AutoDetected"] = "Auto-detected",
        ["Label.Language"] = "Language:",
        ["Label.Scope"] = "Scope:",
        ["Label.SearchFolderDrive"] = "Search folder/drive:",
        ["Label.BpmRange"] = "BPM Range",
        ["Label.ConcurrentTracks"] = "# concurrent tracks to analyse",
        ["Label.KeyNotation"] = "Key Notation",
        ["Label.PlaylistExplanation"] = "How playlists are chosen: the utility first looks for an existing playlist path that matches the selected folder and its parent folders. Example: selecting C:\\Users\\you\\Music\\Folder 2 updates Music/Folder 2 if that playlist already exists. If no matching playlist path exists, the selected folder name is created/used as the root collection. Subfolders are created underneath the detected target. Click Preview to review tracks first, then import only the checked files.",
        ["Label.MissingHelp"] = "Missing files are scanned automatically when this window opens. Tick missing rows to delete them, or select a search folder/drive and click Locate Checked Files to search all subfolders for same-named audio files and update the database path. If files were deliberately moved to another folder, Locate can repair the paths, but moved files may later appear under another playlist when importing from a different subfolder, creating duplicates. To prevent duplicates, delete the missing tracks from the library here, then add them again using the Import window.",
        ["Label.ImportPreviewHeader"] = "Review the tracks that will be imported into the folder collection. Uncheck anything you do not want included, then click Import checked tracks.",

        ["Status.Ready"] = "Ready",
        ["Status.Error"] = "Error",
        ["Status.ScanningPreview"] = "Scanning for preview...",
        ["Status.ImportingSelected"] = "Importing selected tracks...",
        ["Status.ImportComplete"] = "Import complete",
        ["Status.ImportCompleteDetails"] = "Import complete. Files imported: {0}. New tracks: {1}. Playlist entries added: {2}.",
        ["Status.ScanPreparing"] = "Scan progress: preparing file list...",
        ["Status.ScanNoAudio"] = "Scan progress: no audio files found",
        ["Status.ImportNoFiles"] = "Import progress: no files selected",
        ["Status.FindingFiles"] = "{0} - finding files ({1} found): {2}",
        ["Status.ProgressItem"] = "{0} - {1}/{2}: {3}",
        ["Status.Stage"] = "Stage {0} of {1} - {2}",
        ["Status.StageWorking"] = "Working",
        ["Status.Complete"] = "Complete: {0}/{0}",
        ["Status.CheckingMissing"] = "Checking missing files...",
        ["Status.CheckComplete"] = "Check complete",
        ["Status.CheckCompleteDetails"] = "Check complete. Tracks checked: {0}. Missing files: {1}.",
        ["Status.ProgressIdle"] = "Progress: idle",
        ["Status.ProgressNoTracksChecked"] = "Progress: no tracks checked",
        ["Status.ProgressNoTracksSelected"] = "Progress: no tracks selected",
        ["Status.ProgressCount"] = "Progress: {0}/{1}",
        ["Status.CheckingItem"] = "Checking {0}/{1}: {2}",
        ["Status.LocatingMissing"] = "Locating checked missing files...",
        ["Status.LocateCompleteDetails"] = "Locate complete. Updated: {0}. Not found: {1}. Ambiguous: {2}.",
        ["Status.DeletingMissing"] = "Deleting checked missing tracks...",
        ["Status.DeletedMissing"] = "Checked missing tracks deleted",

        ["Dialog.SelectDbTitle"] = "Select Engine DJ m.db",
        ["Dialog.DbFilter"] = "Engine DJ database (*.db)|*.db|All files (*.*)|*.*",
        ["Dialog.SelectImportFolder"] = "Select the parent folder to import, for example C:\\Music\\Test",
        ["Dialog.MissingDatabaseTitle"] = "Missing database",
        ["Dialog.MissingDatabaseMessage"] = "Select a valid Engine DJ m.db file.",
        ["Dialog.MissingImportFolderTitle"] = "Missing import folder",
        ["Dialog.MissingImportFolderMessage"] = "Select a valid import folder.",
        ["Dialog.EngineRunningTitle"] = "Engine DJ is running",
        ["Dialog.EngineRunningMessage"] = "Engine DJ.exe is currently running. Close Engine DJ before changing the database, then click OK to check again. Click Cancel to stop this action.",
        ["Dialog.LoadPlaylistsTitle"] = "Load playlists",
        ["Dialog.MissingScopeTitle"] = "Missing scope",
        ["Dialog.MissingScopeMessage"] = "Select a check scope first.",
        ["Dialog.SelectRepairFolder"] = "Select the drive or folder to search for missing audio files. All subfolders will be searched.",
        ["Dialog.NoTracksSelectedTitle"] = "No tracks selected",
        ["Dialog.SelectTrackImport"] = "Select at least one track to import.",
        ["Dialog.TickTracksLocate"] = "Tick one or more missing tracks to locate first.",
        ["Dialog.TickTracksDelete"] = "Tick one or more missing tracks to delete first.",
        ["Dialog.MissingSearchFolderTitle"] = "Missing search folder",
        ["Dialog.MissingSearchFolderMessage"] = "Select a valid search folder or drive first.",
        ["Dialog.LocateMissingTitle"] = "Locate missing files",
        ["Dialog.LocateMissingConfirm"] = "This will search all subfolders of:\n\n{0}\n\nfor same-named files matching {1} checked missing track(s). When exactly one matching filename is found, the Track.path entry in the Engine DJ database will be updated. A database backup will be created first. Continue?",
        ["Dialog.DeleteMissingTitle"] = "Delete missing tracks from database",
        ["Dialog.DeleteMissingConfirm"] = "This will remove {0} missing track record(s) from the Engine DJ database and remove their playlist entries. No audio files will be deleted. Continue?",

        ["Form.MissingFilesTitle"] = "Missing Files",
        ["Form.ImportPreviewTitle"] = "Preview Import Tracks",

        ["Grid.TrackId"] = "Track ID",
        ["Grid.Title"] = "Title",
        ["Grid.Artist"] = "Artist",
        ["Grid.StoredDbPath"] = "Stored DB path",
        ["Grid.CheckedDiskPath"] = "Checked disk path",
        ["Grid.Status"] = "Status",
        ["Grid.Filename"] = "Filename",
        ["Grid.FolderUnderCollection"] = "Folder under collection",
        ["Grid.StoredEnginePath"] = "Stored Engine path",

        ["Preview.Status.AlreadyInDatabase"] = "Already in DB",
        ["Preview.Status.RelocatedExisting"] = "Relocated existing",
        ["Preview.Status.NewTrack"] = "New track",
        ["Preview.Root"] = "<root>",
        ["Preview.Was"] = "was {0}",
        ["Preview.Section.New"] = "NEW TRACKS - selected by default ({0})",
        ["Preview.Section.Relocated"] = "RELOCATED EXISTING TRACKS - selected to repair path/playlists ({0})",
        ["Preview.Section.Existing"] = "EXISTING TRACKS - not selected by default ({0})",
        ["Preview.Summary"] = "Selected: {0}/{1}. New: {2}/{3}. Relocated: {4}/{5}. Existing: {6}/{7}. New and relocated tracks are selected by default.",

        ["Scope.EntireCollection"] = "Entire Engine Library / Collection: all tracks",

        ["Button.SyncPlaylists"] = "Sync Playlists to Drive...",
        ["Button.PreviewSync"] = "Preview Sync",
        ["Button.CopyFilesToDrive"] = "Copy Files to Drive",
        ["Button.Close"] = "Close",
        ["Label.DestinationDrive"] = "Removable drive:",
        ["Label.ConcurrentCopies"] = "Concurrent copies:",
        ["Label.CopySpeed"] = "Speed: {0}",
        ["Label.PlaylistSyncHelp"] = "Playlist sync: select the playlists you want to sync, choose a detected removable destination drive, then click Preview Sync. If the preview looks correct, click Sync Selected Playlist to copy any missing audio files and create/update those playlists in the drive's Engine DJ database. If the drive does not already contain an Engine DJ database, one will be created. Existing databases are backed up first. Unselected playlists, tracks, and audio files are not deleted.",
        ["Group.Playlists"] = "Playlists to sync",
        ["Grid.Playlist"] = "Playlist",
        ["Grid.SourceFile"] = "Source file",
        ["Grid.DestinationFile"] = "Destination file",
        ["Form.PlaylistSyncTitle"] = "Sync Playlists to Drive",
        ["Status.PlaylistSyncReady"] = "Select playlists and a removable destination drive, then click Preview Sync. After preview, copy files if required.",
        ["Status.NoRemovableDrives"] = "No removable drives detected. Plug in an external drive and click Refresh Drives.",
        ["Status.BuildingPlaylistSyncPreview"] = "Building playlist sync preview...",
        ["Status.PlaylistSyncPreviewSummary"] = "Selected playlists: {0}. Playlist entries: {1}. Unique tracks: {2}. Files to copy: {3}. Already on destination: {4}. Source files missing: {5}. Destination DB: {6} ({7})",
        ["Status.CopyingPlaylistSyncFiles"] = "Copying files: {0}/{1}...",
        ["Status.CopyingCurrentPlaylistSyncFile"] = "Copying ({0}/{1} done): {2} ({3:0}% - {4} of {5})",
        ["Status.CopyFilesComplete"] = "Copy complete. Copied: {0}. Skipped: {1}. Failed: {2}. Destination database was not changed.",
        ["Dialog.SelectDestinationDrive"] = "Select a detected removable destination drive.",
        ["Dialog.NoPlaylistsSelectedTitle"] = "No playlists selected",
        ["Dialog.NoPlaylistsSelectedMessage"] = "Select one or more playlists to preview first.",
        ["Dialog.MissingDestinationTitle"] = "Missing destination",
        ["Dialog.MissingDestinationMessage"] = "Select a detected removable destination drive first.",
        ["Dialog.CopyFilesTitle"] = "Copy files to drive",
        ["Dialog.CopyFilesConfirm"] = "This will copy {0} file(s), requiring approximately {1}, to:\n\n{2}\n\nThe destination Engine DJ database will not be changed yet. Continue?",
        ["Dialog.CopyFilesCompleted"] = "Copy complete. Copied: {0}. Skipped: {1}. The destination Engine DJ database was not changed.",
        ["Dialog.CopyFilesCompletedWithErrors"] = "Copy finished with errors. Copied: {0}. Skipped: {1}. Failed: {2}. Check the log for details. The destination Engine DJ database was not changed.",
        ["Dialog.NoFilesToCopyTitle"] = "No files to copy",
        ["Dialog.NoFilesToCopyMessage"] = "There are no copyable files in the current preview. Run Preview Sync again if the destination has changed.",
        ["Dialog.NotEnoughSpaceTitle"] = "Not enough space",
        ["Dialog.NotEnoughSpaceMessage"] = "The selected drive does not appear to have enough free space. Required: {0}. Available: {1}.",
        ["PlaylistSync.Status.WouldCopy"] = "Would copy",
        ["PlaylistSync.Status.AlreadyOnDrive"] = "Already on drive",
        ["PlaylistSync.Status.SourceMissing"] = "Source missing",
        ["PlaylistSync.Status.Copied"] = "Copied",
        ["PlaylistSync.DatabaseFound"] = "found",
        ["PlaylistSync.DatabaseNotFound"] = "not found - will be created",
        ["PlaylistSync.RemovableDrive"] = "Removable Drive",
        ["PlaylistSync.DriveDisplay"] = "{0} - {1} ({2} free of {3})",
        ["Log.PlaylistsLoaded"] = "Loaded {0} playlist(s).",
        ["Log.RemovableDrivesLoaded"] = "Detected {0} removable drive(s).",
        ["Log.BuildingPlaylistSyncPreview"] = "Building preview for {0} selected playlist(s)...",
        ["Log.CopyingPlaylistSyncFiles"] = "Copying {0} file(s) to the selected drive using up to {1} concurrent copy worker(s)...",
        ["Log.CopyingFile"] = "Copying: {0}",
        ["Log.CopyFileFailed"] = "Copy failed for {0}: {1}",
        ["Log.CopyFilesPerformance"] = "Copied {0} in {1:0.0} seconds ({2}).",
        ["Button.UpdateDestinationDatabase"] = "Update Drive Database",
        ["Button.SyncSelectedPlaylists"] = "Sync Selected Playlist",
        ["Status.UpdatingPlaylistSyncDatabase"] = "Updating destination Engine DJ database...",
        ["Status.UpdatingPlaylistSyncDatabaseProgress"] = "Updating destination database: playlist {0}/{1} - {2}",
        ["Status.UpdateDatabaseComplete"] = "Database update complete. Selected playlists: {0}. Playlist rows written: {1}. Playlists created: {2}. New tracks: {3}. Existing tracks used: {4}. Rows skipped because files were missing: {5}.",
        ["Status.SyncSelectedPlaylistsStarting"] = "Starting selected playlist sync...",
        ["Status.CopyFilesCompleteForSync"] = "File copy stage complete. Copied: {0}. Skipped: {1}. Failed: {2}. Updating database next...",
        ["Status.SyncSelectedPlaylistsComplete"] = "Sync complete. Files copied: {0}. Files skipped: {1}. File failures: {2}. Playlist rows written: {3}. Playlists created: {4}. New tracks: {5}. Existing tracks used: {6}. Rows skipped because files were missing: {7}.",
        ["Dialog.UpdateDatabaseTitle"] = "Update drive database",
        ["Dialog.SyncSelectedPlaylistsTitle"] = "Sync selected playlists",
        ["Dialog.UpdateDatabaseConfirm"] = "This will update the Engine DJ database on the selected drive for {0} selected playlist(s):\n\n{1}\n\nA database backup will be created first in the backups folder at the root of the selected drive. Existing membership for the selected playlists will be replaced. Unselected playlists, tracks, and audio files will not be deleted.\n\nFiles still missing from the drive: {2}. Missing files will be skipped. Continue?",
        ["Dialog.DestinationDatabaseNotFoundTitle"] = "Destination database not found",
        ["Dialog.DestinationDatabaseNotFoundMessage"] = "The selected drive does not contain an Engine DJ database at:\n\n{0}\n\nUse a drive that has already been prepared by Engine DJ, then refresh and preview again.",
        ["Dialog.CreateDatabaseConfirm"] = "No Engine DJ database was found on the selected drive. This will create a new Engine DJ database for {0} selected playlist(s) at:\n\n{1}\n\nThe source database schema will be used as a clean template, then only the selected playlists and their available tracks will be added. Files still missing from the drive: {2}. Missing files will be skipped. Continue?",
        ["Dialog.SyncSelectedPlaylistsConfirm"] = "This will sync {0} selected playlist(s) to the selected removable drive.\n\nFiles to copy: {1} ({2})\nFiles currently missing from the drive: {3}\nDatabase action: {4}\n\nDatabase path:\n{5}\n\nExisting destination databases are backed up first to the backups folder at the root of the selected drive. Existing membership for the selected playlists will be replaced. Unselected playlists, tracks, and audio files will not be deleted. Continue?",
        ["Dialog.SyncSelectedPlaylistsCompleted"] = "Sync complete. Files copied: {0}. Files skipped: {1}. Playlist rows written: {2}.\n\nDatabase updated:\n{3}",
        ["Dialog.SyncSelectedPlaylistsCompletedWithWarnings"] = "Sync complete with warnings. Files copied: {0}. Files skipped: {1}. File failures: {2}. Playlist rows written: {3}. Rows skipped because files were missing from the drive: {4}. Analysis copy failures: {5}.\n\nCheck the log for details.",
        ["Dialog.RunPreviewBeforeSyncTitle"] = "Preview required",
        ["Dialog.RunPreviewBeforeSyncMessage"] = "Run Preview Sync before syncing selected playlists.",
        ["Dialog.UpdateDatabaseCompleted"] = "Database update complete. Playlist rows written: {0}.\n\nBackup created:\n{1}",
        ["Dialog.CreateDatabaseCompleted"] = "Destination database created and updated. Playlist rows written: {0}.\n\nDatabase created:\n{1}",
        ["Dialog.CreateDatabaseCompletedWithMissing"] = "Destination database created and updated with skipped rows. Playlist rows written: {0}. Rows skipped because files were missing from the drive: {1}.\n\nDatabase created:\n{2}",
        ["Dialog.UpdateDatabaseCompletedWithMissing"] = "Database update complete with skipped rows. Playlist rows written: {0}. Rows skipped because files were missing from the drive: {1}.\n\nBackup created:\n{2}",
        ["Log.UpdatingPlaylistSyncDatabase"] = "Updating destination database for {0} selected playlist(s): {1}",
        ["Log.DestinationDatabaseBackup"] = "Destination database backup: {0}",
        ["Log.DestinationDatabaseCreated"] = "Destination database created: {0}",
        ["Log.PlaylistSyncAnalysisCopied"] = "Analysis copied from source DB. Performance rows: {0}. Track analysis fields: {1}. Overview cache files: {2}. Source tracks without analysis rows: {3}. Copy failures: {4}.",
        ["Log.NoPlaylistSyncFilesToCopy"] = "No audio files need copying. Updating the drive database only.",
        ["PlaylistSync.DatabaseWillUpdate"] = "update existing database",
        ["PlaylistSync.DatabaseWillCreate"] = "create new database",
        ["KeyNotation.Sharps"] = "Sharps",
        ["KeyNotation.Flats"] = "Flats",
        ["KeyNotation.OpenKey"] = "Open Key",
        ["KeyNotation.Camelot"] = "Camelot"
    };

    private static readonly Dictionary<string, string> Spanish = new(StringComparer.Ordinal)
    {
        ["Language.System"] = "Predeterminado del sistema",
        ["Language.English"] = "Inglés",
        ["Language.Spanish"] = "Español",
        ["Language.French"] = "Francés",
        ["Language.German"] = "Alemán",
        ["App.Title"] = "Sincronización de importación de carpetas de Engine DJ",
        ["Button.Browse"] = "Examinar...",
        ["Button.Preview"] = "Vista previa",
        ["Button.MissingFiles"] = "Archivos faltantes",
        ["Button.RefreshPlaylists"] = "Actualizar listas",
        ["Button.RefreshDrives"] = "Actualizar discos",
        ["Button.DeleteCheckedMissing"] = "Eliminar pistas faltantes marcadas",
        ["Button.LocateCheckedFiles"] = "Localizar archivos marcados...",
        ["Button.ImportCheckedTracks"] = "Importar pistas marcadas",
        ["Button.Cancel"] = "Cancelar",
        ["CheckBox.DarkMode"] = "Modo oscuro",
        ["CheckBox.Analysis"] = "Generar análisis de BPM/forma de onda para las pistas marcadas",
        ["CheckBox.KeyDetection"] = "Incluir detección de tonalidad",
        ["CheckBox.OfficialAnalyzer"] = "Usar Engine DJ OfflineAnalyzer oficial",
        ["CheckBox.OfficialAnalyzerNotFound"] = "Engine DJ OfflineAnalyzer oficial no se encontró en este equipo",
        ["CheckBox.CaptureOfficialAnalyzer"] = "Guardar captura del analizador oficial + datos de forma de onda decodificados",
        ["Label.PrimaryDb"] = "Base de datos principal de Engine (m.db):",
        ["Label.ImportFolder"] = "Carpeta de importación:",
        ["Label.UpdateTarget"] = "Destino de actualización:",
        ["Label.AutoDetected"] = "Detectado automáticamente",
        ["Label.Language"] = "Idioma:",
        ["Label.Scope"] = "Ámbito:",
        ["Label.SearchFolderDrive"] = "Carpeta/unidad de búsqueda:",
        ["Label.BpmRange"] = "Rango de BPM",
        ["Label.ConcurrentTracks"] = "N.º de pistas concurrentes para analizar",
        ["Label.KeyNotation"] = "Notación de tonalidad",
        ["Label.PlaylistExplanation"] = "Cómo se eligen las listas: la utilidad primero busca una ruta de lista existente que coincida con la carpeta seleccionada y sus carpetas principales. Ejemplo: al seleccionar C:\\Users\\you\\Music\\Folder 2 se actualiza Music/Folder 2 si esa lista ya existe. Si no existe una ruta de lista coincidente, el nombre de la carpeta seleccionada se crea/usa como colección raíz. Las subcarpetas se crean debajo del destino detectado. Haz clic en Vista previa para revisar las pistas primero y luego importa solo los archivos marcados.",
        ["Label.MissingHelp"] = "Los archivos faltantes se analizan automáticamente cuando se abre esta ventana. Marca las filas faltantes para eliminarlas, o selecciona una carpeta/unidad de búsqueda y haz clic en Localizar archivos marcados para buscar en todas las subcarpetas archivos de audio con el mismo nombre y actualizar la ruta en la base de datos. Si los archivos se movieron deliberadamente a otra carpeta, Localizar puede reparar las rutas, pero esos archivos podrían aparecer luego bajo otra lista al importar desde una subcarpeta distinta, creando duplicados. Para evitar duplicados, elimina aquí las pistas faltantes de la biblioteca y vuelve a añadirlas desde la ventana Importar.",
        ["Label.ImportPreviewHeader"] = "Revisa las pistas que se importarán a la colección de la carpeta. Desmarca lo que no quieras incluir y luego haz clic en Importar pistas marcadas.",
        ["Status.Ready"] = "Listo",
        ["Status.Error"] = "Error",
        ["Status.ScanningPreview"] = "Analizando para vista previa...",
        ["Status.ImportingSelected"] = "Importando pistas seleccionadas...",
        ["Status.ImportComplete"] = "Importación completa",
        ["Status.ImportCompleteDetails"] = "Importación completa. Archivos importados: {0}. Pistas nuevas: {1}. Entradas de lista añadidas: {2}.",
        ["Status.ScanPreparing"] = "Progreso del análisis: preparando lista de archivos...",
        ["Status.ScanNoAudio"] = "Progreso del análisis: no se encontraron archivos de audio",
        ["Status.ImportNoFiles"] = "Progreso de importación: no hay archivos seleccionados",
        ["Status.FindingFiles"] = "{0} - buscando archivos ({1} encontrados): {2}",
        ["Status.ProgressItem"] = "{0} - {1}/{2}: {3}",
        ["Status.Stage"] = "Etapa {0} de {1} - {2}",
        ["Status.StageWorking"] = "Trabajando",
        ["Status.Complete"] = "Completo: {0}/{0}",
        ["Status.CheckingMissing"] = "Comprobando archivos faltantes...",
        ["Status.CheckComplete"] = "Comprobación completa",
        ["Status.CheckCompleteDetails"] = "Comprobación completa. Pistas comprobadas: {0}. Archivos faltantes: {1}.",
        ["Status.ProgressIdle"] = "Progreso: inactivo",
        ["Status.ProgressNoTracksChecked"] = "Progreso: no se comprobaron pistas",
        ["Status.ProgressNoTracksSelected"] = "Progreso: no hay pistas seleccionadas",
        ["Status.ProgressCount"] = "Progreso: {0}/{1}",
        ["Status.CheckingItem"] = "Comprobando {0}/{1}: {2}",
        ["Status.LocatingMissing"] = "Localizando archivos faltantes marcados...",
        ["Status.LocateCompleteDetails"] = "Localización completa. Actualizados: {0}. No encontrados: {1}. Ambiguos: {2}.",
        ["Status.DeletingMissing"] = "Eliminando pistas faltantes marcadas...",
        ["Status.DeletedMissing"] = "Pistas faltantes marcadas eliminadas",
        ["Dialog.SelectDbTitle"] = "Seleccionar m.db de Engine DJ",
        ["Dialog.DbFilter"] = "Base de datos de Engine DJ (*.db)|*.db|Todos los archivos (*.*)|*.*",
        ["Dialog.SelectImportFolder"] = "Selecciona la carpeta principal que se va a importar, por ejemplo C:\\Music\\Test",
        ["Dialog.MissingDatabaseTitle"] = "Base de datos faltante",
        ["Dialog.MissingDatabaseMessage"] = "Selecciona un archivo m.db de Engine DJ válido.",
        ["Dialog.MissingImportFolderTitle"] = "Carpeta de importación faltante",
        ["Dialog.MissingImportFolderMessage"] = "Selecciona una carpeta de importación válida.",
        ["Dialog.EngineRunningTitle"] = "Engine DJ se está ejecutando",
        ["Dialog.EngineRunningMessage"] = "Engine DJ.exe se está ejecutando. Cierra Engine DJ antes de cambiar la base de datos y luego haz clic en Aceptar para volver a comprobar. Haz clic en Cancelar para detener esta acción.",
        ["Dialog.LoadPlaylistsTitle"] = "Cargar listas",
        ["Dialog.MissingScopeTitle"] = "Ámbito faltante",
        ["Dialog.MissingScopeMessage"] = "Selecciona primero un ámbito de comprobación.",
        ["Dialog.SelectRepairFolder"] = "Selecciona la unidad o carpeta donde buscar archivos de audio faltantes. Se buscará en todas las subcarpetas.",
        ["Dialog.NoTracksSelectedTitle"] = "No hay pistas seleccionadas",
        ["Dialog.SelectTrackImport"] = "Selecciona al menos una pista para importar.",
        ["Dialog.TickTracksLocate"] = "Marca una o más pistas faltantes para localizarlas primero.",
        ["Dialog.TickTracksDelete"] = "Marca una o más pistas faltantes para eliminarlas primero.",
        ["Dialog.MissingSearchFolderTitle"] = "Carpeta de búsqueda faltante",
        ["Dialog.MissingSearchFolderMessage"] = "Selecciona primero una carpeta o unidad de búsqueda válida.",
        ["Dialog.LocateMissingTitle"] = "Localizar archivos faltantes",
        ["Dialog.LocateMissingConfirm"] = "Esto buscará en todas las subcarpetas de:\n\n{0}\n\narchivos con el mismo nombre que coincidan con {1} pista(s) faltante(s) marcada(s). Cuando se encuentre exactamente un archivo coincidente, se actualizará la entrada Track.path en la base de datos de Engine DJ. Primero se creará una copia de seguridad de la base de datos. ¿Continuar?",
        ["Dialog.DeleteMissingTitle"] = "Eliminar pistas faltantes de la base de datos",
        ["Dialog.DeleteMissingConfirm"] = "Esto eliminará {0} registro(s) de pista faltante de la base de datos de Engine DJ y sus entradas de lista. No se eliminará ningún archivo de audio. ¿Continuar?",
        ["Form.MissingFilesTitle"] = "Archivos faltantes",
        ["Form.ImportPreviewTitle"] = "Vista previa de pistas a importar",
        ["Grid.TrackId"] = "ID de pista",
        ["Grid.Title"] = "Título",
        ["Grid.Artist"] = "Artista",
        ["Grid.StoredDbPath"] = "Ruta guardada en BD",
        ["Grid.CheckedDiskPath"] = "Ruta comprobada en disco",
        ["Grid.Status"] = "Estado",
        ["Grid.Filename"] = "Nombre de archivo",
        ["Grid.FolderUnderCollection"] = "Carpeta dentro de la colección",
        ["Grid.StoredEnginePath"] = "Ruta guardada de Engine",
        ["Preview.Status.AlreadyInDatabase"] = "Ya está en la BD",
        ["Preview.Status.RelocatedExisting"] = "Existente reubicada",
        ["Preview.Status.NewTrack"] = "Pista nueva",
        ["Preview.Root"] = "<raíz>",
        ["Preview.Was"] = "antes {0}",
        ["Preview.Section.New"] = "PISTAS NUEVAS - seleccionadas por defecto ({0})",
        ["Preview.Section.Relocated"] = "PISTAS EXISTENTES REUBICADAS - seleccionadas para reparar ruta/listas ({0})",
        ["Preview.Section.Existing"] = "PISTAS EXISTENTES - no seleccionadas por defecto ({0})",
        ["Preview.Summary"] = "Seleccionadas: {0}/{1}. Nuevas: {2}/{3}. Reubicadas: {4}/{5}. Existentes: {6}/{7}. Las pistas nuevas y reubicadas se seleccionan por defecto.",
        ["Scope.EntireCollection"] = "Toda la biblioteca/colección de Engine: todas las pistas",
        ["Button.SyncPlaylists"] = "Sincronizar listas al disco...",
        ["Button.PreviewSync"] = "Vista previa de sincronización",
        ["Button.CopyFilesToDrive"] = "Copiar archivos al disco",
        ["Button.Close"] = "Cerrar",
        ["Label.DestinationDrive"] = "Disco extraíble:",
        ["Label.ConcurrentCopies"] = "Copias simultáneas:",
        ["Label.CopySpeed"] = "Velocidad: {0}",
        ["Label.PlaylistSyncHelp"] = "Sincronización de listas: seleccione las listas que desea sincronizar, elija un disco extraíble detectado y haga clic en Vista previa de sincronización. Si la vista previa es correcta, haga clic en Sincronizar listas seleccionadas para copiar los archivos de audio faltantes y crear/actualizar esas listas en la base de datos Engine DJ del disco. Se crea una copia de seguridad primero. No se eliminan listas no seleccionadas, pistas ni archivos de audio.",
        ["Group.Playlists"] = "Listas para sincronizar",
        ["Grid.Playlist"] = "Lista",
        ["Grid.SourceFile"] = "Archivo de origen",
        ["Grid.DestinationFile"] = "Archivo de destino",
        ["Form.PlaylistSyncTitle"] = "Sincronizar listas al disco",
        ["Status.PlaylistSyncReady"] = "Seleccione listas y un disco extraíble de destino, luego haga clic en Vista previa de sincronización. Después de la vista previa, copie archivos si es necesario.",
        ["Status.NoRemovableDrives"] = "No se detectaron discos extraíbles. Conecte un disco externo y haga clic en Actualizar discos.",
        ["Status.BuildingPlaylistSyncPreview"] = "Creando vista previa de sincronización de listas...",
        ["Status.PlaylistSyncPreviewSummary"] = "Listas seleccionadas: {0}. Entradas de lista: {1}. Pistas únicas: {2}. Archivos para copiar: {3}. Ya en destino: {4}. Archivos de origen faltantes: {5}. BD de destino: {6} ({7})",
        ["Status.CopyingPlaylistSyncFiles"] = "Copiando archivos: {0}/{1}...",
        ["Status.CopyingCurrentPlaylistSyncFile"] = "Copiando ({0}/{1} completados): {2} ({3:0}% - {4} de {5})",
        ["Status.CopyFilesComplete"] = "Copia completa. Copiados: {0}. Omitidos: {1}. Fallidos: {2}. La base de datos de destino no se modificó.",
        ["Dialog.SelectDestinationDrive"] = "Seleccione un disco extraíble de destino detectado.",
        ["Dialog.NoPlaylistsSelectedTitle"] = "No hay listas seleccionadas",
        ["Dialog.NoPlaylistsSelectedMessage"] = "Seleccione una o más listas para previsualizar primero.",
        ["Dialog.MissingDestinationTitle"] = "Destino faltante",
        ["Dialog.MissingDestinationMessage"] = "Seleccione primero un disco extraíble de destino detectado.",
        ["Dialog.CopyFilesTitle"] = "Copiar archivos al disco",
        ["Dialog.CopyFilesConfirm"] = "Esto copiará {0} archivo(s), con un tamaño aproximado de {1}, en:\n\n{2}\n\nLa base de datos de Engine DJ de destino aún no se modificará. ¿Continuar?",
        ["Dialog.CopyFilesCompleted"] = "Copia completa. Copiados: {0}. Omitidos: {1}. La base de datos de Engine DJ de destino no se modificó.",
        ["Dialog.CopyFilesCompletedWithErrors"] = "La copia terminó con errores. Copiados: {0}. Omitidos: {1}. Fallidos: {2}. Revisa el registro para ver detalles. La base de datos de Engine DJ de destino no se modificó.",
        ["Dialog.NoFilesToCopyTitle"] = "No hay archivos para copiar",
        ["Dialog.NoFilesToCopyMessage"] = "No hay archivos copiables en la vista previa actual. Ejecuta Vista previa de sincronización otra vez si el destino ha cambiado.",
        ["Dialog.NotEnoughSpaceTitle"] = "No hay espacio suficiente",
        ["Dialog.NotEnoughSpaceMessage"] = "El disco seleccionado no parece tener suficiente espacio libre. Requerido: {0}. Disponible: {1}.",
        ["PlaylistSync.Status.WouldCopy"] = "Se copiaría",
        ["PlaylistSync.Status.AlreadyOnDrive"] = "Ya está en el disco",
        ["PlaylistSync.Status.SourceMissing"] = "Origen faltante",
        ["PlaylistSync.Status.Copied"] = "Copiado",
        ["PlaylistSync.DatabaseFound"] = "encontrada",
        ["PlaylistSync.DatabaseNotFound"] = "no encontrada - se creará",
        ["PlaylistSync.RemovableDrive"] = "Disco extraíble",
        ["PlaylistSync.DriveDisplay"] = "{0} - {1} ({2} libres de {3})",
        ["Log.PlaylistsLoaded"] = "Se cargaron {0} lista(s).",
        ["Log.RemovableDrivesLoaded"] = "Se detectaron {0} disco(s) extraíble(s).",
        ["Log.BuildingPlaylistSyncPreview"] = "Creando vista previa para {0} lista(s) seleccionada(s)...",
        ["Log.CopyingPlaylistSyncFiles"] = "Copiando {0} archivo(s) al disco seleccionado usando hasta {1} tarea(s) simultánea(s)...",
        ["Log.CopyingFile"] = "Copiando: {0}",
        ["Log.CopyFileFailed"] = "Error al copiar {0}: {1}",
        ["Log.CopyFilesPerformance"] = "Copiados {0} en {1:0.0} segundos ({2}).",
        ["Button.UpdateDestinationDatabase"] = "Actualizar base de datos del disco",
        ["Button.SyncSelectedPlaylists"] = "Sincronizar listas seleccionadas",
        ["Status.UpdatingPlaylistSyncDatabase"] = "Actualizando la base de datos Engine DJ de destino...",
        ["Status.UpdatingPlaylistSyncDatabaseProgress"] = "Actualizando base de datos de destino: lista {0}/{1} - {2}",
        ["Status.UpdateDatabaseComplete"] = "Actualización de base de datos completa. Listas seleccionadas: {0}. Filas de lista escritas: {1}. Listas creadas: {2}. Pistas nuevas: {3}. Pistas existentes usadas: {4}. Filas omitidas por archivos faltantes: {5}.",
        ["Status.SyncSelectedPlaylistsStarting"] = "Iniciando sincronización de listas seleccionadas...",
        ["Status.CopyFilesCompleteForSync"] = "Etapa de copia completa. Copiados: {0}. Omitidos: {1}. Fallidos: {2}. Actualizando la base de datos...",
        ["Status.SyncSelectedPlaylistsComplete"] = "Sincronización completa. Archivos copiados: {0}. Archivos omitidos: {1}. Fallos de archivo: {2}. Filas de lista escritas: {3}. Listas creadas: {4}. Pistas nuevas: {5}. Pistas existentes usadas: {6}. Filas omitidas por archivos faltantes: {7}.",
        ["Dialog.UpdateDatabaseTitle"] = "Actualizar base de datos del disco",
        ["Dialog.SyncSelectedPlaylistsTitle"] = "Sincronizar listas seleccionadas",
        ["Dialog.UpdateDatabaseConfirm"] = "Esto actualizará la base de datos Engine DJ del disco seleccionado para {0} lista(s) seleccionada(s):\n\n{1}\n\nPrimero se creará una copia de seguridad en la carpeta backups de la raíz del disco seleccionado. Se reemplazará la pertenencia existente de las listas seleccionadas. No se eliminarán listas no seleccionadas, pistas ni archivos de audio.\n\nArchivos que aún faltan en el disco: {2}. Los archivos faltantes se omitirán. ¿Continuar?",
        ["Dialog.DestinationDatabaseNotFoundTitle"] = "Base de datos de destino no encontrada",
        ["Dialog.DestinationDatabaseNotFoundMessage"] = "El disco seleccionado no contiene una base de datos Engine DJ en:\n\n{0}\n\nUse un disco preparado previamente por Engine DJ, luego actualice y previsualice de nuevo.",
        ["Dialog.CreateDatabaseConfirm"] = "No se encontró una base de datos Engine DJ en el disco seleccionado. Esto creará una nueva base de datos Engine DJ para {0} lista(s) seleccionada(s) en:\n\n{1}\n\nSe usará el esquema de la base de datos de origen como plantilla limpia y luego solo se añadirán las listas seleccionadas y sus pistas disponibles. Archivos aún faltantes en el disco: {2}. Los archivos faltantes se omitirán. ¿Continuar?",
        ["Dialog.SyncSelectedPlaylistsConfirm"] = "Esto sincronizará {0} lista(s) seleccionada(s) con el disco extraíble seleccionado.\n\nArchivos a copiar: {1} ({2})\nArchivos que faltan actualmente en el disco: {3}\nAcción de base de datos: {4}\n\nRuta de base de datos:\n{5}\n\nLas bases de datos existentes se respaldan primero en la carpeta backups de la raíz del disco seleccionado. Se reemplazará la pertenencia existente de las listas seleccionadas. No se eliminarán listas no seleccionadas, pistas ni archivos de audio. ¿Continuar?",
        ["Dialog.SyncSelectedPlaylistsCompleted"] = "Sincronización completa. Archivos copiados: {0}. Archivos omitidos: {1}. Filas de lista escritas: {2}.\n\nBase de datos actualizada:\n{3}",
        ["Dialog.SyncSelectedPlaylistsCompletedWithWarnings"] = "Sincronización completa con advertencias. Archivos copiados: {0}. Archivos omitidos: {1}. Fallos de archivo: {2}. Filas de lista escritas: {3}. Filas omitidas porque faltaban archivos en el disco: {4}. Fallos al copiar análisis: {5}.\n\nRevise el registro para más detalles.",
        ["Dialog.RunPreviewBeforeSyncTitle"] = "Vista previa requerida",
        ["Dialog.RunPreviewBeforeSyncMessage"] = "Ejecute Vista previa de sincronización antes de sincronizar las listas seleccionadas.",
        ["Dialog.UpdateDatabaseCompleted"] = "Actualización de base de datos completa. Filas de lista escritas: {0}.\n\nCopia de seguridad creada:\n{1}",
        ["Dialog.CreateDatabaseCompleted"] = "Base de datos de destino creada y actualizada. Filas de lista escritas: {0}.\n\nBase de datos creada:\n{1}",
        ["Dialog.CreateDatabaseCompletedWithMissing"] = "Base de datos de destino creada y actualizada con filas omitidas. Filas de lista escritas: {0}. Filas omitidas porque faltaban archivos en el disco: {1}.\n\nBase de datos creada:\n{2}",
        ["Dialog.UpdateDatabaseCompletedWithMissing"] = "Actualización completa con filas omitidas. Filas de lista escritas: {0}. Filas omitidas porque faltaban archivos en el disco: {1}.\n\nCopia de seguridad creada:\n{2}",
        ["Log.UpdatingPlaylistSyncDatabase"] = "Actualizando base de datos de destino para {0} lista(s) seleccionada(s): {1}",
        ["Log.DestinationDatabaseBackup"] = "Copia de seguridad de la base de datos de destino: {0}",
        ["Log.DestinationDatabaseCreated"] = "Base de datos de destino creada: {0}",
        ["Log.PlaylistSyncAnalysisCopied"] = "Análisis copiado desde la base de datos de origen. Filas de rendimiento: {0}. Campos de análisis de pista: {1}. Archivos de caché de vista general: {2}. Pistas de origen sin filas de análisis: {3}. Errores de copia: {4}.",
        ["Log.NoPlaylistSyncFilesToCopy"] = "No hay archivos de audio que copiar. Actualizando solo la base de datos del disco.",
        ["PlaylistSync.DatabaseWillUpdate"] = "actualizar la base de datos existente",
        ["PlaylistSync.DatabaseWillCreate"] = "crear una nueva base de datos",
        ["KeyNotation.Sharps"] = "Sostenidos",
        ["KeyNotation.Flats"] = "Bemoles",
        ["KeyNotation.OpenKey"] = "Open Key",
        ["KeyNotation.Camelot"] = "Camelot"
    };

    private static readonly Dictionary<string, string> French = new(StringComparer.Ordinal)
    {
        ["Language.System"] = "Par défaut du système",
        ["Language.English"] = "Anglais",
        ["Language.Spanish"] = "Espagnol",
        ["Language.French"] = "Français",
        ["Language.German"] = "Allemand",
        ["App.Title"] = "Synchronisation d'importation de dossiers Engine DJ",
        ["Button.Browse"] = "Parcourir...",
        ["Button.Preview"] = "Aperçu",
        ["Button.MissingFiles"] = "Fichiers manquants",
        ["Button.RefreshPlaylists"] = "Actualiser les playlists",
        ["Button.RefreshDrives"] = "Actualiser les disques",
        ["Button.DeleteCheckedMissing"] = "Supprimer les pistes manquantes cochées",
        ["Button.LocateCheckedFiles"] = "Localiser les fichiers cochés...",
        ["Button.ImportCheckedTracks"] = "Importer les pistes cochées",
        ["Button.Cancel"] = "Annuler",
        ["CheckBox.DarkMode"] = "Mode sombre",
        ["CheckBox.Analysis"] = "Générer l'analyse BPM/forme d'onde pour les pistes cochées",
        ["CheckBox.KeyDetection"] = "Inclure la détection de tonalité",
        ["CheckBox.OfficialAnalyzer"] = "Utiliser Engine DJ OfflineAnalyzer officiel",
        ["CheckBox.OfficialAnalyzerNotFound"] = "Engine DJ OfflineAnalyzer officiel est introuvable sur cet ordinateur",
        ["CheckBox.CaptureOfficialAnalyzer"] = "Enregistrer la capture de l'analyseur officiel + les données de forme d'onde décodées",
        ["Label.PrimaryDb"] = "Base Engine principale (m.db) :",
        ["Label.ImportFolder"] = "Dossier d'importation :",
        ["Label.UpdateTarget"] = "Cible de mise à jour :",
        ["Label.AutoDetected"] = "Détecté automatiquement",
        ["Label.Language"] = "Langue :",
        ["Label.Scope"] = "Portée :",
        ["Label.SearchFolderDrive"] = "Dossier/lecteur de recherche :",
        ["Label.BpmRange"] = "Plage BPM",
        ["Label.ConcurrentTracks"] = "Nombre de pistes à analyser en parallèle",
        ["Label.KeyNotation"] = "Notation de tonalité",
        ["Label.PlaylistExplanation"] = "Choix des playlists : l'utilitaire recherche d'abord un chemin de playlist existant qui correspond au dossier sélectionné et à ses dossiers parents. Exemple : sélectionner C:\\Users\\you\\Music\\Folder 2 met à jour Music/Folder 2 si cette playlist existe déjà. Si aucun chemin de playlist correspondant n'existe, le nom du dossier sélectionné est créé/utilisé comme collection racine. Les sous-dossiers sont créés sous la cible détectée. Cliquez sur Aperçu pour vérifier les pistes, puis importez uniquement les fichiers cochés.",
        ["Label.MissingHelp"] = "Les fichiers manquants sont analysés automatiquement à l'ouverture de cette fenêtre. Cochez les lignes manquantes pour les supprimer, ou sélectionnez un dossier/lecteur de recherche et cliquez sur Localiser les fichiers cochés pour rechercher dans tous les sous-dossiers les fichiers audio portant le même nom et mettre à jour le chemin dans la base de données. Si les fichiers ont été volontairement déplacés vers un autre dossier, Localiser peut réparer les chemins, mais les fichiers déplacés peuvent ensuite apparaître sous une autre playlist lors d'une importation depuis un autre sous-dossier, créant des doublons. Pour éviter les doublons, supprimez ici les pistes manquantes de la bibliothèque, puis ajoutez-les à nouveau depuis la fenêtre Importer.",
        ["Label.ImportPreviewHeader"] = "Vérifiez les pistes qui seront importées dans la collection du dossier. Décochez ce que vous ne voulez pas inclure, puis cliquez sur Importer les pistes cochées.",
        ["Status.Ready"] = "Prêt",
        ["Status.Error"] = "Erreur",
        ["Status.ScanningPreview"] = "Analyse pour aperçu...",
        ["Status.ImportingSelected"] = "Importation des pistes sélectionnées...",
        ["Status.ImportComplete"] = "Importation terminée",
        ["Status.ImportCompleteDetails"] = "Importation terminée. Fichiers importés : {0}. Nouvelles pistes : {1}. Entrées de playlist ajoutées : {2}.",
        ["Status.ScanPreparing"] = "Progression de l'analyse : préparation de la liste des fichiers...",
        ["Status.ScanNoAudio"] = "Progression de l'analyse : aucun fichier audio trouvé",
        ["Status.ImportNoFiles"] = "Progression de l'importation : aucun fichier sélectionné",
        ["Status.FindingFiles"] = "{0} - recherche des fichiers ({1} trouvés) : {2}",
        ["Status.ProgressItem"] = "{0} - {1}/{2} : {3}",
        ["Status.Stage"] = "Étape {0} sur {1} - {2}",
        ["Status.StageWorking"] = "Traitement",
        ["Status.Complete"] = "Terminé : {0}/{0}",
        ["Status.CheckingMissing"] = "Vérification des fichiers manquants...",
        ["Status.CheckComplete"] = "Vérification terminée",
        ["Status.CheckCompleteDetails"] = "Vérification terminée. Pistes vérifiées : {0}. Fichiers manquants : {1}.",
        ["Status.ProgressIdle"] = "Progression : inactif",
        ["Status.ProgressNoTracksChecked"] = "Progression : aucune piste vérifiée",
        ["Status.ProgressNoTracksSelected"] = "Progression : aucune piste sélectionnée",
        ["Status.ProgressCount"] = "Progression : {0}/{1}",
        ["Status.CheckingItem"] = "Vérification {0}/{1} : {2}",
        ["Status.LocatingMissing"] = "Localisation des fichiers manquants cochés...",
        ["Status.LocateCompleteDetails"] = "Localisation terminée. Mis à jour : {0}. Introuvables : {1}. Ambigus : {2}.",
        ["Status.DeletingMissing"] = "Suppression des pistes manquantes cochées...",
        ["Status.DeletedMissing"] = "Pistes manquantes cochées supprimées",
        ["Dialog.SelectDbTitle"] = "Sélectionner le m.db d'Engine DJ",
        ["Dialog.DbFilter"] = "Base de données Engine DJ (*.db)|*.db|Tous les fichiers (*.*)|*.*",
        ["Dialog.SelectImportFolder"] = "Sélectionnez le dossier parent à importer, par exemple C:\\Music\\Test",
        ["Dialog.MissingDatabaseTitle"] = "Base de données manquante",
        ["Dialog.MissingDatabaseMessage"] = "Sélectionnez un fichier m.db Engine DJ valide.",
        ["Dialog.MissingImportFolderTitle"] = "Dossier d'importation manquant",
        ["Dialog.MissingImportFolderMessage"] = "Sélectionnez un dossier d'importation valide.",
        ["Dialog.EngineRunningTitle"] = "Engine DJ est en cours d'exécution",
        ["Dialog.EngineRunningMessage"] = "Engine DJ.exe est en cours d'exécution. Fermez Engine DJ avant de modifier la base de données, puis cliquez sur OK pour vérifier à nouveau. Cliquez sur Annuler pour arrêter cette action.",
        ["Dialog.LoadPlaylistsTitle"] = "Charger les playlists",
        ["Dialog.MissingScopeTitle"] = "Portée manquante",
        ["Dialog.MissingScopeMessage"] = "Sélectionnez d'abord une portée de vérification.",
        ["Dialog.SelectRepairFolder"] = "Sélectionnez le lecteur ou le dossier où rechercher les fichiers audio manquants. Tous les sous-dossiers seront parcourus.",
        ["Dialog.NoTracksSelectedTitle"] = "Aucune piste sélectionnée",
        ["Dialog.SelectTrackImport"] = "Sélectionnez au moins une piste à importer.",
        ["Dialog.TickTracksLocate"] = "Cochez d'abord une ou plusieurs pistes manquantes à localiser.",
        ["Dialog.TickTracksDelete"] = "Cochez d'abord une ou plusieurs pistes manquantes à supprimer.",
        ["Dialog.MissingSearchFolderTitle"] = "Dossier de recherche manquant",
        ["Dialog.MissingSearchFolderMessage"] = "Sélectionnez d'abord un dossier ou lecteur de recherche valide.",
        ["Dialog.LocateMissingTitle"] = "Localiser les fichiers manquants",
        ["Dialog.LocateMissingConfirm"] = "Cette action recherchera dans tous les sous-dossiers de :\n\n{0}\n\nles fichiers portant le même nom correspondant à {1} piste(s) manquante(s) cochée(s). Lorsqu'un seul fichier correspondant est trouvé, l'entrée Track.path dans la base de données Engine DJ sera mise à jour. Une sauvegarde de la base de données sera créée au préalable. Continuer ?",
        ["Dialog.DeleteMissingTitle"] = "Supprimer les pistes manquantes de la base de données",
        ["Dialog.DeleteMissingConfirm"] = "Cette action supprimera {0} enregistrement(s) de piste manquante de la base de données Engine DJ ainsi que leurs entrées de playlist. Aucun fichier audio ne sera supprimé. Continuer ?",
        ["Form.MissingFilesTitle"] = "Fichiers manquants",
        ["Form.ImportPreviewTitle"] = "Aperçu des pistes à importer",
        ["Grid.TrackId"] = "ID piste",
        ["Grid.Title"] = "Titre",
        ["Grid.Artist"] = "Artiste",
        ["Grid.StoredDbPath"] = "Chemin BD enregistré",
        ["Grid.CheckedDiskPath"] = "Chemin disque vérifié",
        ["Grid.Status"] = "État",
        ["Grid.Filename"] = "Nom du fichier",
        ["Grid.FolderUnderCollection"] = "Dossier dans la collection",
        ["Grid.StoredEnginePath"] = "Chemin Engine enregistré",
        ["Preview.Status.AlreadyInDatabase"] = "Déjà en BD",
        ["Preview.Status.RelocatedExisting"] = "Existant déplacé",
        ["Preview.Status.NewTrack"] = "Nouvelle piste",
        ["Preview.Root"] = "<racine>",
        ["Preview.Was"] = "était {0}",
        ["Preview.Section.New"] = "NOUVELLES PISTES - sélectionnées par défaut ({0})",
        ["Preview.Section.Relocated"] = "PISTES EXISTANTES DÉPLACÉES - sélectionnées pour réparer chemin/playlists ({0})",
        ["Preview.Section.Existing"] = "PISTES EXISTANTES - non sélectionnées par défaut ({0})",
        ["Preview.Summary"] = "Sélectionnées : {0}/{1}. Nouvelles : {2}/{3}. Déplacées : {4}/{5}. Existantes : {6}/{7}. Les pistes nouvelles et déplacées sont sélectionnées par défaut.",
        ["Scope.EntireCollection"] = "Bibliothèque / collection Engine complète : toutes les pistes",
        ["Button.SyncPlaylists"] = "Synchroniser les playlists vers le disque...",
        ["Button.PreviewSync"] = "Prévisualiser la synchronisation",
        ["Button.CopyFilesToDrive"] = "Copier les fichiers vers le disque",
        ["Button.Close"] = "Fermer",
        ["Label.DestinationDrive"] = "Disque amovible :",
        ["Label.ConcurrentCopies"] = "Copies simultanées :",
        ["Label.CopySpeed"] = "Vitesse : {0}",
        ["Label.PlaylistSyncHelp"] = "Synchronisation des playlists : sélectionnez les playlists à synchroniser, choisissez un disque amovible détecté, puis cliquez sur Prévisualiser la synchronisation. Si l'aperçu est correct, cliquez sur Synchroniser les playlists sélectionnées pour copier les fichiers audio manquants et créer/mettre à jour ces playlists dans la base Engine DJ du disque. Une sauvegarde est créée au préalable. Les playlists non sélectionnées, les pistes et les fichiers audio ne sont pas supprimés.",
        ["Group.Playlists"] = "Playlists à synchroniser",
        ["Grid.Playlist"] = "Playlist",
        ["Grid.SourceFile"] = "Fichier source",
        ["Grid.DestinationFile"] = "Fichier de destination",
        ["Form.PlaylistSyncTitle"] = "Synchroniser les playlists vers le disque",
        ["Status.PlaylistSyncReady"] = "Sélectionnez les playlists et un disque amovible de destination, puis cliquez sur Prévisualiser la synchronisation. Après l'aperçu, copiez les fichiers si nécessaire.",
        ["Status.NoRemovableDrives"] = "Aucun disque amovible détecté. Branchez un disque externe puis cliquez sur Actualiser les disques.",
        ["Status.BuildingPlaylistSyncPreview"] = "Création de l'aperçu de synchronisation des playlists...",
        ["Status.PlaylistSyncPreviewSummary"] = "Playlists sélectionnées : {0}. Entrées de playlist : {1}. Titres uniques : {2}. Fichiers à copier : {3}. Déjà sur la destination : {4}. Fichiers source manquants : {5}. BD de destination : {6} ({7})",
        ["Status.CopyingPlaylistSyncFiles"] = "Copie des fichiers : {0}/{1}...",
        ["Status.CopyingCurrentPlaylistSyncFile"] = "Copie ({0}/{1} terminés) : {2} ({3:0} % - {4} sur {5})",
        ["Status.CopyFilesComplete"] = "Copie terminée. Copiés : {0}. Ignorés : {1}. Échecs : {2}. La base de données de destination n'a pas été modifiée.",
        ["Dialog.SelectDestinationDrive"] = "Sélectionnez un disque amovible de destination détecté.",
        ["Dialog.NoPlaylistsSelectedTitle"] = "Aucune playlist sélectionnée",
        ["Dialog.NoPlaylistsSelectedMessage"] = "Sélectionnez d'abord une ou plusieurs playlists à prévisualiser.",
        ["Dialog.MissingDestinationTitle"] = "Destination manquante",
        ["Dialog.MissingDestinationMessage"] = "Sélectionnez d'abord un disque amovible de destination détecté.",
        ["Dialog.CopyFilesTitle"] = "Copier les fichiers vers le disque",
        ["Dialog.CopyFilesConfirm"] = "Cela copiera {0} fichier(s), soit environ {1}, vers :\n\n{2}\n\nLa base de données Engine DJ de destination ne sera pas encore modifiée. Continuer ?",
        ["Dialog.CopyFilesCompleted"] = "Copie terminée. Copiés : {0}. Ignorés : {1}. La base de données Engine DJ de destination n'a pas été modifiée.",
        ["Dialog.CopyFilesCompletedWithErrors"] = "La copie s'est terminée avec des erreurs. Copiés : {0}. Ignorés : {1}. Échecs : {2}. Consultez le journal pour plus de détails. La base de données Engine DJ de destination n'a pas été modifiée.",
        ["Dialog.NoFilesToCopyTitle"] = "Aucun fichier à copier",
        ["Dialog.NoFilesToCopyMessage"] = "Aucun fichier copiable dans l'aperçu actuel. Relancez Prévisualiser la synchronisation si la destination a changé.",
        ["Dialog.NotEnoughSpaceTitle"] = "Espace insuffisant",
        ["Dialog.NotEnoughSpaceMessage"] = "Le disque sélectionné ne semble pas disposer de suffisamment d'espace libre. Requis : {0}. Disponible : {1}.",
        ["PlaylistSync.Status.WouldCopy"] = "À copier",
        ["PlaylistSync.Status.AlreadyOnDrive"] = "Déjà sur le disque",
        ["PlaylistSync.Status.SourceMissing"] = "Source manquante",
        ["PlaylistSync.Status.Copied"] = "Copié",
        ["PlaylistSync.DatabaseFound"] = "trouvée",
        ["PlaylistSync.DatabaseNotFound"] = "introuvable - sera créée",
        ["PlaylistSync.RemovableDrive"] = "Disque amovible",
        ["PlaylistSync.DriveDisplay"] = "{0} - {1} ({2} libres sur {3})",
        ["Log.PlaylistsLoaded"] = "{0} playlist(s) chargée(s).",
        ["Log.RemovableDrivesLoaded"] = "{0} disque(s) amovible(s) détecté(s).",
        ["Log.BuildingPlaylistSyncPreview"] = "Création de l'aperçu pour {0} playlist(s) sélectionnée(s)...",
        ["Log.CopyingPlaylistSyncFiles"] = "Copie de {0} fichier(s) vers le disque sélectionné avec jusqu’à {1} tâche(s) simultanée(s)...",
        ["Log.CopyingFile"] = "Copie : {0}",
        ["Log.CopyFileFailed"] = "Échec de la copie de {0} : {1}",
        ["Log.CopyFilesPerformance"] = "Copié {0} en {1:0.0} secondes ({2}).",
        ["Button.UpdateDestinationDatabase"] = "Mettre à jour la base du disque",
        ["Button.SyncSelectedPlaylists"] = "Synchroniser les playlists sélectionnées",
        ["Status.UpdatingPlaylistSyncDatabase"] = "Mise à jour de la base Engine DJ de destination...",
        ["Status.UpdatingPlaylistSyncDatabaseProgress"] = "Mise à jour de la base de destination : playlist {0}/{1} - {2}",
        ["Status.UpdateDatabaseComplete"] = "Mise à jour de la base terminée. Playlists sélectionnées : {0}. Lignes de playlist écrites : {1}. Playlists créées : {2}. Nouvelles pistes : {3}. Pistes existantes utilisées : {4}. Lignes ignorées car fichiers manquants : {5}.",
        ["Status.SyncSelectedPlaylistsStarting"] = "Démarrage de la synchronisation des playlists sélectionnées...",
        ["Status.CopyFilesCompleteForSync"] = "Étape de copie terminée. Copiés : {0}. Ignorés : {1}. Échecs : {2}. Mise à jour de la base...",
        ["Status.SyncSelectedPlaylistsComplete"] = "Synchronisation terminée. Fichiers copiés : {0}. Fichiers ignorés : {1}. Échecs fichier : {2}. Lignes de playlist écrites : {3}. Playlists créées : {4}. Nouvelles pistes : {5}. Pistes existantes utilisées : {6}. Lignes ignorées car fichiers manquants : {7}.",
        ["Dialog.UpdateDatabaseTitle"] = "Mettre à jour la base du disque",
        ["Dialog.SyncSelectedPlaylistsTitle"] = "Synchroniser les playlists sélectionnées",
        ["Dialog.UpdateDatabaseConfirm"] = "Cela mettra à jour la base Engine DJ du disque sélectionné pour {0} playlist(s) sélectionnée(s) :\n\n{1}\n\nUne sauvegarde sera d'abord créée dans le dossier backups à la racine du disque sélectionné. Les appartenances existantes des playlists sélectionnées seront remplacées. Les playlists non sélectionnées, les pistes et les fichiers audio ne seront pas supprimés.\n\nFichiers encore manquants sur le disque : {2}. Les fichiers manquants seront ignorés. Continuer ?",
        ["Dialog.DestinationDatabaseNotFoundTitle"] = "Base de destination introuvable",
        ["Dialog.DestinationDatabaseNotFoundMessage"] = "Le disque sélectionné ne contient pas de base Engine DJ à cet emplacement :\n\n{0}\n\nUtilisez un disque déjà préparé par Engine DJ, puis actualisez et prévisualisez à nouveau.",
        ["Dialog.CreateDatabaseConfirm"] = "Aucune base Engine DJ n'a été trouvée sur le disque sélectionné. Une nouvelle base Engine DJ sera créée pour {0} playlist(s) sélectionnée(s) à cet emplacement :\n\n{1}\n\nLe schéma de la base source sera utilisé comme modèle propre, puis seules les playlists sélectionnées et leurs pistes disponibles seront ajoutées. Fichiers encore manquants sur le disque : {2}. Les fichiers manquants seront ignorés. Continuer ?",
        ["Dialog.SyncSelectedPlaylistsConfirm"] = "Cela synchronisera {0} playlist(s) sélectionnée(s) vers le disque amovible sélectionné.\n\nFichiers à copier : {1} ({2})\nFichiers actuellement manquants sur le disque : {3}\nAction base de données : {4}\n\nChemin de la base :\n{5}\n\nLes bases de destination existantes sont d'abord sauvegardées dans le dossier backups à la racine du disque sélectionné. L'appartenance existante des playlists sélectionnées sera remplacée. Les playlists non sélectionnées, les pistes et les fichiers audio ne seront pas supprimés. Continuer ?",
        ["Dialog.SyncSelectedPlaylistsCompleted"] = "Synchronisation terminée. Fichiers copiés : {0}. Fichiers ignorés : {1}. Lignes de playlist écrites : {2}.\n\nBase mise à jour :\n{3}",
        ["Dialog.SyncSelectedPlaylistsCompletedWithWarnings"] = "Synchronisation terminée avec avertissements. Fichiers copiés : {0}. Fichiers ignorés : {1}. Échecs fichier : {2}. Lignes de playlist écrites : {3}. Lignes ignorées car des fichiers manquaient sur le disque : {4}. Échecs de copie d'analyse : {5}.\n\nConsultez le journal pour plus de détails.",
        ["Dialog.RunPreviewBeforeSyncTitle"] = "Aperçu requis",
        ["Dialog.RunPreviewBeforeSyncMessage"] = "Exécutez Prévisualiser la synchronisation avant de synchroniser les playlists sélectionnées.",
        ["Dialog.UpdateDatabaseCompleted"] = "Mise à jour de la base terminée. Lignes de playlist écrites : {0}.\n\nSauvegarde créée :\n{1}",
        ["Dialog.CreateDatabaseCompleted"] = "Base de destination créée et mise à jour. Lignes de playlist écrites : {0}.\n\nBase créée :\n{1}",
        ["Dialog.CreateDatabaseCompletedWithMissing"] = "Base de destination créée et mise à jour avec des lignes ignorées. Lignes de playlist écrites : {0}. Lignes ignorées car les fichiers étaient absents du disque : {1}.\n\nBase créée :\n{2}",
        ["Dialog.UpdateDatabaseCompletedWithMissing"] = "Mise à jour terminée avec des lignes ignorées. Lignes de playlist écrites : {0}. Lignes ignorées car des fichiers manquaient sur le disque : {1}.\n\nSauvegarde créée :\n{2}",
        ["Log.UpdatingPlaylistSyncDatabase"] = "Mise à jour de la base de destination pour {0} playlist(s) sélectionnée(s) : {1}",
        ["Log.DestinationDatabaseBackup"] = "Sauvegarde de la base de destination : {0}",
        ["Log.DestinationDatabaseCreated"] = "Base de destination créée : {0}",
        ["Log.PlaylistSyncAnalysisCopied"] = "Analyse copiée depuis la base source. Lignes de performance : {0}. Champs d’analyse de piste : {1}. Fichiers de cache d’aperçu : {2}. Pistes source sans lignes d’analyse : {3}. Échecs de copie : {4}.",
        ["Log.NoPlaylistSyncFilesToCopy"] = "Aucun fichier audio à copier. Mise à jour de la base du disque uniquement.",
        ["PlaylistSync.DatabaseWillUpdate"] = "mettre à jour la base existante",
        ["PlaylistSync.DatabaseWillCreate"] = "créer une nouvelle base",
        ["KeyNotation.Sharps"] = "Dièses",
        ["KeyNotation.Flats"] = "Bémols",
        ["KeyNotation.OpenKey"] = "Open Key",
        ["KeyNotation.Camelot"] = "Camelot"
    };

    private static readonly Dictionary<string, string> German = new(StringComparer.Ordinal)
    {
        ["Language.System"] = "Systemstandard",
        ["Language.English"] = "Englisch",
        ["Language.Spanish"] = "Spanisch",
        ["Language.French"] = "Französisch",
        ["Language.German"] = "Deutsch",
        ["App.Title"] = "Engine DJ Ordnerimport-Synchronisierung",
        ["Button.Browse"] = "Durchsuchen...",
        ["Button.Preview"] = "Vorschau",
        ["Button.MissingFiles"] = "Fehlende Dateien",
        ["Button.RefreshPlaylists"] = "Playlists aktualisieren",
        ["Button.RefreshDrives"] = "Laufwerke aktualisieren",
        ["Button.DeleteCheckedMissing"] = "Markierte fehlende Titel löschen",
        ["Button.LocateCheckedFiles"] = "Markierte Dateien suchen...",
        ["Button.ImportCheckedTracks"] = "Markierte Titel importieren",
        ["Button.Cancel"] = "Abbrechen",
        ["CheckBox.DarkMode"] = "Dunkler Modus",
        ["CheckBox.Analysis"] = "BPM-/Wellenformanalyse für markierte Titel erzeugen",
        ["CheckBox.KeyDetection"] = "Tonarterkennung einschließen",
        ["CheckBox.OfficialAnalyzer"] = "Offiziellen Engine DJ OfflineAnalyzer verwenden",
        ["CheckBox.OfficialAnalyzerNotFound"] = "Offizieller Engine DJ OfflineAnalyzer wurde auf diesem Computer nicht gefunden",
        ["CheckBox.CaptureOfficialAnalyzer"] = "Offizielle Analyzer-Aufzeichnung + dekodierte Wellenformdaten speichern",
        ["Label.PrimaryDb"] = "Primäre Engine-Datenbank (m.db):",
        ["Label.ImportFolder"] = "Importordner:",
        ["Label.UpdateTarget"] = "Aktualisierungsziel:",
        ["Label.AutoDetected"] = "Automatisch erkannt",
        ["Label.Language"] = "Sprache:",
        ["Label.Scope"] = "Bereich:",
        ["Label.SearchFolderDrive"] = "Suchordner/-laufwerk:",
        ["Label.BpmRange"] = "BPM-Bereich",
        ["Label.ConcurrentTracks"] = "Anzahl gleichzeitig zu analysierender Titel",
        ["Label.KeyNotation"] = "Tonartnotation",
        ["Label.PlaylistExplanation"] = "So werden Playlists ausgewählt: Das Tool sucht zuerst nach einem vorhandenen Playlist-Pfad, der zum ausgewählten Ordner und seinen übergeordneten Ordnern passt. Beispiel: Wenn C:\\Users\\you\\Music\\Folder 2 ausgewählt wird, wird Music/Folder 2 aktualisiert, falls diese Playlist bereits vorhanden ist. Wenn kein passender Playlist-Pfad existiert, wird der Name des ausgewählten Ordners als Root-Sammlung erstellt/verwendet. Unterordner werden unterhalb des erkannten Ziels erstellt. Klicken Sie auf Vorschau, um die Titel zuerst zu prüfen, und importieren Sie dann nur die markierten Dateien.",
        ["Label.MissingHelp"] = "Fehlende Dateien werden beim Öffnen dieses Fensters automatisch geprüft. Markieren Sie fehlende Zeilen, um sie zu löschen, oder wählen Sie einen Suchordner/ein Laufwerk und klicken Sie auf Markierte Dateien suchen, um alle Unterordner nach gleichnamigen Audiodateien zu durchsuchen und den Datenbankpfad zu aktualisieren. Wenn Dateien absichtlich in einen anderen Ordner verschoben wurden, kann Suchen die Pfade reparieren. Verschobene Dateien können jedoch später beim Import aus einem anderen Unterordner unter einer anderen Playlist erscheinen und Duplikate erzeugen. Um Duplikate zu vermeiden, löschen Sie die fehlenden Titel hier aus der Bibliothek und fügen Sie sie anschließend über das Importfenster erneut hinzu.",
        ["Label.ImportPreviewHeader"] = "Prüfen Sie die Titel, die in die Ordnersammlung importiert werden. Entfernen Sie die Markierung für alles, was nicht enthalten sein soll, und klicken Sie dann auf Markierte Titel importieren.",
        ["Status.Ready"] = "Bereit",
        ["Status.Error"] = "Fehler",
        ["Status.ScanningPreview"] = "Scanne für Vorschau...",
        ["Status.ImportingSelected"] = "Importiere ausgewählte Titel...",
        ["Status.ImportComplete"] = "Import abgeschlossen",
        ["Status.ImportCompleteDetails"] = "Import abgeschlossen. Dateien importiert: {0}. Neue Titel: {1}. Playlist-Einträge hinzugefügt: {2}.",
        ["Status.ScanPreparing"] = "Scanfortschritt: Dateiliste wird vorbereitet...",
        ["Status.ScanNoAudio"] = "Scanfortschritt: keine Audiodateien gefunden",
        ["Status.ImportNoFiles"] = "Importfortschritt: keine Dateien ausgewählt",
        ["Status.FindingFiles"] = "{0} - suche Dateien ({1} gefunden): {2}",
        ["Status.ProgressItem"] = "{0} - {1}/{2}: {3}",
        ["Status.Stage"] = "Stufe {0} von {1} - {2}",
        ["Status.StageWorking"] = "In Arbeit",
        ["Status.Complete"] = "Fertig: {0}/{0}",
        ["Status.CheckingMissing"] = "Prüfe fehlende Dateien...",
        ["Status.CheckComplete"] = "Prüfung abgeschlossen",
        ["Status.CheckCompleteDetails"] = "Prüfung abgeschlossen. Titel geprüft: {0}. Fehlende Dateien: {1}.",
        ["Status.ProgressIdle"] = "Fortschritt: inaktiv",
        ["Status.ProgressNoTracksChecked"] = "Fortschritt: keine Titel geprüft",
        ["Status.ProgressNoTracksSelected"] = "Fortschritt: keine Titel ausgewählt",
        ["Status.ProgressCount"] = "Fortschritt: {0}/{1}",
        ["Status.CheckingItem"] = "Prüfe {0}/{1}: {2}",
        ["Status.LocatingMissing"] = "Suche markierte fehlende Dateien...",
        ["Status.LocateCompleteDetails"] = "Suche abgeschlossen. Aktualisiert: {0}. Nicht gefunden: {1}. Mehrdeutig: {2}.",
        ["Status.DeletingMissing"] = "Lösche markierte fehlende Titel...",
        ["Status.DeletedMissing"] = "Markierte fehlende Titel gelöscht",
        ["Dialog.SelectDbTitle"] = "Engine DJ m.db auswählen",
        ["Dialog.DbFilter"] = "Engine DJ-Datenbank (*.db)|*.db|Alle Dateien (*.*)|*.*",
        ["Dialog.SelectImportFolder"] = "Wählen Sie den übergeordneten Ordner für den Import aus, z. B. C:\\Music\\Test",
        ["Dialog.MissingDatabaseTitle"] = "Datenbank fehlt",
        ["Dialog.MissingDatabaseMessage"] = "Wählen Sie eine gültige Engine DJ m.db-Datei aus.",
        ["Dialog.MissingImportFolderTitle"] = "Importordner fehlt",
        ["Dialog.MissingImportFolderMessage"] = "Wählen Sie einen gültigen Importordner aus.",
        ["Dialog.EngineRunningTitle"] = "Engine DJ läuft",
        ["Dialog.EngineRunningMessage"] = "Engine DJ.exe wird gerade ausgeführt. Schließen Sie Engine DJ, bevor Sie die Datenbank ändern, und klicken Sie dann auf OK, um erneut zu prüfen. Klicken Sie auf Abbrechen, um diese Aktion zu stoppen.",
        ["Dialog.LoadPlaylistsTitle"] = "Playlists laden",
        ["Dialog.MissingScopeTitle"] = "Bereich fehlt",
        ["Dialog.MissingScopeMessage"] = "Wählen Sie zuerst einen Prüfbereich aus.",
        ["Dialog.SelectRepairFolder"] = "Wählen Sie das Laufwerk oder den Ordner aus, in dem nach fehlenden Audiodateien gesucht werden soll. Alle Unterordner werden durchsucht.",
        ["Dialog.NoTracksSelectedTitle"] = "Keine Titel ausgewählt",
        ["Dialog.SelectTrackImport"] = "Wählen Sie mindestens einen Titel für den Import aus.",
        ["Dialog.TickTracksLocate"] = "Markieren Sie zuerst einen oder mehrere fehlende Titel zum Suchen.",
        ["Dialog.TickTracksDelete"] = "Markieren Sie zuerst einen oder mehrere fehlende Titel zum Löschen.",
        ["Dialog.MissingSearchFolderTitle"] = "Suchordner fehlt",
        ["Dialog.MissingSearchFolderMessage"] = "Wählen Sie zuerst einen gültigen Suchordner oder ein Laufwerk aus.",
        ["Dialog.LocateMissingTitle"] = "Fehlende Dateien suchen",
        ["Dialog.LocateMissingConfirm"] = "Dadurch werden alle Unterordner von:\n\n{0}\n\nnach gleichnamigen Dateien durchsucht, die zu {1} markierten fehlenden Titel(n) passen. Wenn genau ein passender Dateiname gefunden wird, wird der Track.path-Eintrag in der Engine DJ-Datenbank aktualisiert. Zuerst wird eine Datenbanksicherung erstellt. Fortfahren?",
        ["Dialog.DeleteMissingTitle"] = "Fehlende Titel aus der Datenbank löschen",
        ["Dialog.DeleteMissingConfirm"] = "Dadurch werden {0} fehlende Titeldatensätze aus der Engine DJ-Datenbank und deren Playlist-Einträge entfernt. Es werden keine Audiodateien gelöscht. Fortfahren?",
        ["Form.MissingFilesTitle"] = "Fehlende Dateien",
        ["Form.ImportPreviewTitle"] = "Importtitel-Vorschau",
        ["Grid.TrackId"] = "Titel-ID",
        ["Grid.Title"] = "Titel",
        ["Grid.Artist"] = "Künstler",
        ["Grid.StoredDbPath"] = "Gespeicherter DB-Pfad",
        ["Grid.CheckedDiskPath"] = "Geprüfter Datenträgerpfad",
        ["Grid.Status"] = "Status",
        ["Grid.Filename"] = "Dateiname",
        ["Grid.FolderUnderCollection"] = "Ordner in der Sammlung",
        ["Grid.StoredEnginePath"] = "Gespeicherter Engine-Pfad",
        ["Preview.Status.AlreadyInDatabase"] = "Bereits in DB",
        ["Preview.Status.RelocatedExisting"] = "Verschoben vorhanden",
        ["Preview.Status.NewTrack"] = "Neuer Titel",
        ["Preview.Root"] = "<Stamm>",
        ["Preview.Was"] = "war {0}",
        ["Preview.Section.New"] = "NEUE TITEL - standardmäßig ausgewählt ({0})",
        ["Preview.Section.Relocated"] = "VERSCHOBENE VORHANDENE TITEL - ausgewählt, um Pfad/Playlists zu reparieren ({0})",
        ["Preview.Section.Existing"] = "VORHANDENE TITEL - standardmäßig nicht ausgewählt ({0})",
        ["Preview.Summary"] = "Ausgewählt: {0}/{1}. Neu: {2}/{3}. Verschoben: {4}/{5}. Vorhanden: {6}/{7}. Neue und verschobene Titel sind standardmäßig ausgewählt.",
        ["Scope.EntireCollection"] = "Gesamte Engine-Bibliothek/-Sammlung: alle Titel",
        ["Button.SyncPlaylists"] = "Playlists auf Laufwerk synchronisieren...",
        ["Button.PreviewSync"] = "Synchronisierungsvorschau",
        ["Button.CopyFilesToDrive"] = "Dateien auf Laufwerk kopieren",
        ["Button.Close"] = "Schließen",
        ["Label.DestinationDrive"] = "Wechseldatenträger:",
        ["Label.ConcurrentCopies"] = "Gleichzeitige Kopien:",
        ["Label.CopySpeed"] = "Geschwindigkeit: {0}",
        ["Label.PlaylistSyncHelp"] = "Playlist-Synchronisierung: Wählen Sie die zu synchronisierenden Playlists aus, wählen Sie einen erkannten Wechseldatenträger und klicken Sie auf Synchronisierungsvorschau. Wenn die Vorschau korrekt ist, klicken Sie auf Ausgewählte Playlists synchronisieren, um fehlende Audiodateien zu kopieren und diese Playlists in der Engine DJ-Datenbank des Laufwerks zu erstellen/aktualisieren. Zuerst wird eine Sicherung erstellt. Nicht ausgewählte Playlists, Tracks und Audiodateien werden nicht gelöscht.",
        ["Group.Playlists"] = "Zu synchronisierende Playlists",
        ["Grid.Playlist"] = "Playlist",
        ["Grid.SourceFile"] = "Quelldatei",
        ["Grid.DestinationFile"] = "Zieldatei",
        ["Form.PlaylistSyncTitle"] = "Playlists auf Laufwerk synchronisieren",
        ["Status.PlaylistSyncReady"] = "Wählen Sie Playlists und einen Wechseldatenträger als Ziel aus und klicken Sie dann auf Synchronisierungsvorschau. Nach der Vorschau können Sie Dateien kopieren, falls erforderlich.",
        ["Status.NoRemovableDrives"] = "Keine Wechseldatenträger erkannt. Schließen Sie ein externes Laufwerk an und klicken Sie auf Laufwerke aktualisieren.",
        ["Status.BuildingPlaylistSyncPreview"] = "Playlist-Synchronisierungsvorschau wird erstellt...",
        ["Status.PlaylistSyncPreviewSummary"] = "Ausgewählte Playlists: {0}. Playlist-Einträge: {1}. Eindeutige Titel: {2}. Zu kopierende Dateien: {3}. Bereits am Ziel: {4}. Fehlende Quelldateien: {5}. Ziel-DB: {6} ({7})",
        ["Status.CopyingPlaylistSyncFiles"] = "Dateien werden kopiert: {0}/{1}...",
        ["Status.CopyingCurrentPlaylistSyncFile"] = "Kopiere ({0}/{1} fertig): {2} ({3:0}% - {4} von {5})",
        ["Status.CopyFilesComplete"] = "Kopiervorgang abgeschlossen. Kopiert: {0}. Übersprungen: {1}. Fehlgeschlagen: {2}. Die Zieldatenbank wurde nicht geändert.",
        ["Dialog.SelectDestinationDrive"] = "Wählen Sie einen erkannten Wechseldatenträger als Ziel aus.",
        ["Dialog.NoPlaylistsSelectedTitle"] = "Keine Playlists ausgewählt",
        ["Dialog.NoPlaylistsSelectedMessage"] = "Wählen Sie zuerst eine oder mehrere Playlists für die Vorschau aus.",
        ["Dialog.MissingDestinationTitle"] = "Ziel fehlt",
        ["Dialog.MissingDestinationMessage"] = "Wählen Sie zuerst einen erkannten Wechseldatenträger als Ziel aus.",
        ["Dialog.CopyFilesTitle"] = "Dateien auf Laufwerk kopieren",
        ["Dialog.CopyFilesConfirm"] = "Dies kopiert {0} Datei(en), ungefähr {1}, nach:\n\n{2}\n\nDie Engine DJ-Zieldatenbank wird noch nicht geändert. Fortfahren?",
        ["Dialog.CopyFilesCompleted"] = "Kopiervorgang abgeschlossen. Kopiert: {0}. Übersprungen: {1}. Die Engine DJ-Zieldatenbank wurde nicht geändert.",
        ["Dialog.CopyFilesCompletedWithErrors"] = "Der Kopiervorgang wurde mit Fehlern beendet. Kopiert: {0}. Übersprungen: {1}. Fehlgeschlagen: {2}. Details stehen im Protokoll. Die Engine DJ-Zieldatenbank wurde nicht geändert.",
        ["Dialog.NoFilesToCopyTitle"] = "Keine Dateien zu kopieren",
        ["Dialog.NoFilesToCopyMessage"] = "In der aktuellen Vorschau gibt es keine kopierbaren Dateien. Führen Sie die Synchronisierungsvorschau erneut aus, wenn sich das Ziel geändert hat.",
        ["Dialog.NotEnoughSpaceTitle"] = "Nicht genügend Speicherplatz",
        ["Dialog.NotEnoughSpaceMessage"] = "Das ausgewählte Laufwerk scheint nicht genügend freien Speicherplatz zu haben. Erforderlich: {0}. Verfügbar: {1}.",
        ["PlaylistSync.Status.WouldCopy"] = "Würde kopieren",
        ["PlaylistSync.Status.AlreadyOnDrive"] = "Bereits auf Laufwerk",
        ["PlaylistSync.Status.SourceMissing"] = "Quelle fehlt",
        ["PlaylistSync.Status.Copied"] = "Kopiert",
        ["PlaylistSync.DatabaseFound"] = "gefunden",
        ["PlaylistSync.DatabaseNotFound"] = "nicht gefunden - wird erstellt",
        ["PlaylistSync.RemovableDrive"] = "Wechseldatenträger",
        ["PlaylistSync.DriveDisplay"] = "{0} - {1} ({2} frei von {3})",
        ["Log.PlaylistsLoaded"] = "{0} Playlist(s) geladen.",
        ["Log.RemovableDrivesLoaded"] = "{0} Wechseldatenträger erkannt.",
        ["Log.BuildingPlaylistSyncPreview"] = "Erstelle Vorschau für {0} ausgewählte Playlist(s)...",
        ["Log.CopyingPlaylistSyncFiles"] = "Kopiere {0} Datei(en) auf das ausgewählte Laufwerk mit bis zu {1} gleichzeitigen Kopieraufgaben...",
        ["Log.CopyingFile"] = "Kopiere: {0}",
        ["Log.CopyFileFailed"] = "Kopieren fehlgeschlagen für {0}: {1}",
        ["Log.CopyFilesPerformance"] = "{0} in {1:0.0} Sekunden kopiert ({2}).",
        ["Button.UpdateDestinationDatabase"] = "Laufwerksdatenbank aktualisieren",
        ["Button.SyncSelectedPlaylists"] = "Ausgewählte Playlists synchronisieren",
        ["Status.UpdatingPlaylistSyncDatabase"] = "Engine DJ-Zieldatenbank wird aktualisiert...",
        ["Status.UpdatingPlaylistSyncDatabaseProgress"] = "Zieldatenbank wird aktualisiert: Playlist {0}/{1} - {2}",
        ["Status.UpdateDatabaseComplete"] = "Datenbankaktualisierung abgeschlossen. Ausgewählte Playlists: {0}. Geschriebene Playlist-Zeilen: {1}. Erstellte Playlists: {2}. Neue Tracks: {3}. Verwendete vorhandene Tracks: {4}. Übersprungene Zeilen wegen fehlender Dateien: {5}.",
        ["Status.SyncSelectedPlaylistsStarting"] = "Synchronisierung ausgewählter Playlists wird gestartet...",
        ["Status.CopyFilesCompleteForSync"] = "Kopierstufe abgeschlossen. Kopiert: {0}. Übersprungen: {1}. Fehlgeschlagen: {2}. Datenbank wird aktualisiert...",
        ["Status.SyncSelectedPlaylistsComplete"] = "Synchronisierung abgeschlossen. Dateien kopiert: {0}. Dateien übersprungen: {1}. Dateifehler: {2}. Geschriebene Playlist-Zeilen: {3}. Erstellte Playlists: {4}. Neue Tracks: {5}. Verwendete vorhandene Tracks: {6}. Übersprungene Zeilen wegen fehlender Dateien: {7}.",
        ["Dialog.UpdateDatabaseTitle"] = "Laufwerksdatenbank aktualisieren",
        ["Dialog.SyncSelectedPlaylistsTitle"] = "Ausgewählte Playlists synchronisieren",
        ["Dialog.UpdateDatabaseConfirm"] = "Dies aktualisiert die Engine DJ-Datenbank auf dem ausgewählten Laufwerk für {0} ausgewählte Playlist(s):\n\n{1}\n\nZuerst wird eine Datenbanksicherung im Ordner backups im Stammverzeichnis des ausgewählten Laufwerks erstellt. Vorhandene Mitgliedschaften der ausgewählten Playlists werden ersetzt. Nicht ausgewählte Playlists, Tracks und Audiodateien werden nicht gelöscht.\n\nNoch auf dem Laufwerk fehlende Dateien: {2}. Fehlende Dateien werden übersprungen. Fortfahren?",
        ["Dialog.DestinationDatabaseNotFoundTitle"] = "Zieldatenbank nicht gefunden",
        ["Dialog.DestinationDatabaseNotFoundMessage"] = "Das ausgewählte Laufwerk enthält keine Engine DJ-Datenbank unter:\n\n{0}\n\nVerwenden Sie ein Laufwerk, das bereits von Engine DJ vorbereitet wurde, und aktualisieren Sie dann erneut die Vorschau.",
        ["Dialog.CreateDatabaseConfirm"] = "Auf dem ausgewählten Laufwerk wurde keine Engine DJ-Datenbank gefunden. Es wird eine neue Engine DJ-Datenbank für {0} ausgewählte Playlist(s) erstellt unter:\n\n{1}\n\nDas Schema der Quelldatenbank wird als leere Vorlage verwendet, danach werden nur die ausgewählten Playlists und ihre verfügbaren Tracks hinzugefügt. Noch fehlende Dateien auf dem Laufwerk: {2}. Fehlende Dateien werden übersprungen. Fortfahren?",
        ["Dialog.SyncSelectedPlaylistsConfirm"] = "Dadurch werden {0} ausgewählte Playlist(s) auf den ausgewählten Wechseldatenträger synchronisiert.\n\nZu kopierende Dateien: {1} ({2})\nAktuell auf dem Laufwerk fehlende Dateien: {3}\nDatenbankaktion: {4}\n\nDatenbankpfad:\n{5}\n\nVorhandene Zieldatenbanken werden zuerst im Ordner backups im Stammverzeichnis des ausgewählten Laufwerks gesichert. Die vorhandene Mitgliedschaft der ausgewählten Playlists wird ersetzt. Nicht ausgewählte Playlists, Tracks und Audiodateien werden nicht gelöscht. Fortfahren?",
        ["Dialog.SyncSelectedPlaylistsCompleted"] = "Synchronisierung abgeschlossen. Dateien kopiert: {0}. Dateien übersprungen: {1}. Geschriebene Playlist-Zeilen: {2}.\n\nDatenbank aktualisiert:\n{3}",
        ["Dialog.SyncSelectedPlaylistsCompletedWithWarnings"] = "Synchronisierung mit Warnungen abgeschlossen. Dateien kopiert: {0}. Dateien übersprungen: {1}. Dateifehler: {2}. Geschriebene Playlist-Zeilen: {3}. Übersprungene Zeilen wegen fehlender Dateien auf dem Laufwerk: {4}. Fehler beim Kopieren der Analyse: {5}.\n\nDetails stehen im Protokoll.",
        ["Dialog.RunPreviewBeforeSyncTitle"] = "Vorschau erforderlich",
        ["Dialog.RunPreviewBeforeSyncMessage"] = "Führen Sie die Synchronisierungsvorschau aus, bevor Sie ausgewählte Playlists synchronisieren.",
        ["Dialog.UpdateDatabaseCompleted"] = "Datenbankaktualisierung abgeschlossen. Geschriebene Playlist-Zeilen: {0}.\n\nSicherung erstellt:\n{1}",
        ["Dialog.CreateDatabaseCompleted"] = "Zieldatenbank erstellt und aktualisiert. Geschriebene Playlist-Zeilen: {0}.\n\nDatenbank erstellt:\n{1}",
        ["Dialog.CreateDatabaseCompletedWithMissing"] = "Zieldatenbank erstellt und mit übersprungenen Zeilen aktualisiert. Geschriebene Playlist-Zeilen: {0}. Übersprungene Zeilen wegen fehlender Dateien auf dem Laufwerk: {1}.\n\nDatenbank erstellt:\n{2}",
        ["Dialog.UpdateDatabaseCompletedWithMissing"] = "Datenbankaktualisierung mit übersprungenen Zeilen abgeschlossen. Geschriebene Playlist-Zeilen: {0}. Übersprungene Zeilen, weil Dateien auf dem Laufwerk fehlten: {1}.\n\nSicherung erstellt:\n{2}",
        ["Log.UpdatingPlaylistSyncDatabase"] = "Zieldatenbank wird für {0} ausgewählte Playlist(s) aktualisiert: {1}",
        ["Log.DestinationDatabaseBackup"] = "Sicherung der Zieldatenbank: {0}",
        ["Log.DestinationDatabaseCreated"] = "Zieldatenbank erstellt: {0}",
        ["Log.PlaylistSyncAnalysisCopied"] = "Analyse aus der Quelldatenbank kopiert. Performance-Zeilen: {0}. Track-Analysefelder: {1}. Übersicht-Cachedateien: {2}. Quelltracks ohne Analysezeilen: {3}. Kopierfehler: {4}.",
        ["Log.NoPlaylistSyncFilesToCopy"] = "Es müssen keine Audiodateien kopiert werden. Nur die Laufwerksdatenbank wird aktualisiert.",
        ["PlaylistSync.DatabaseWillUpdate"] = "vorhandene Datenbank aktualisieren",
        ["PlaylistSync.DatabaseWillCreate"] = "neue Datenbank erstellen",
        ["KeyNotation.Sharps"] = "Kreuze",
        ["KeyNotation.Flats"] = "Bs",
        ["KeyNotation.OpenKey"] = "Open Key",
        ["KeyNotation.Camelot"] = "Camelot"
    };

    private static readonly Dictionary<string, Dictionary<string, string>> Localized = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = English,
        ["es"] = Spanish,
        ["fr"] = French,
        ["de"] = German
    };

    public static string RequestedLanguageCode { get; private set; } = SystemDefaultLanguage;
    public static string EffectiveLanguageCode { get; private set; } = "en";

    public static void ApplyLanguage(string? requestedLanguageCode)
    {
        RequestedLanguageCode = NormalizeRequestedLanguage(requestedLanguageCode);
        var culture = RequestedLanguageCode == SystemDefaultLanguage
            ? SystemUiCulture
            : CultureInfo.GetCultureInfo(RequestedLanguageCode);

        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        Thread.CurrentThread.CurrentCulture = culture;
        Thread.CurrentThread.CurrentUICulture = culture;
        EffectiveLanguageCode = ResolveEffectiveLanguageCode(culture);
    }

    public static IReadOnlyList<LanguageChoice> GetLanguageChoices() => new[]
    {
        new LanguageChoice(SystemDefaultLanguage, Text("Language.System")),
        new LanguageChoice("en", Text("Language.English")),
        new LanguageChoice("es", Text("Language.Spanish")),
        new LanguageChoice("fr", Text("Language.French")),
        new LanguageChoice("de", Text("Language.German"))
    };

    public static string Text(string key)
    {
        if (Localized.TryGetValue(EffectiveLanguageCode, out var selected) && selected.TryGetValue(key, out var value))
            return value;

        return English.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string Format(string key, params object?[] args) => string.Format(CultureInfo.CurrentUICulture, Text(key), args);

    public static string ImportPreviewStatusText(ImportPreviewStatus status) => status switch
    {
        ImportPreviewStatus.AlreadyInDatabase => Text("Preview.Status.AlreadyInDatabase"),
        ImportPreviewStatus.RelocatedExisting => Text("Preview.Status.RelocatedExisting"),
        _ => Text("Preview.Status.NewTrack")
    };

    public static string LocalizeProgressStageName(string? stageName)
    {
        var normalized = (stageName ?? string.Empty).Trim();
        return normalized switch
        {
            "Working" or "" => Text("Status.StageWorking"),
            _ => normalized
        };
    }

    private static string NormalizeRequestedLanguage(string? requestedLanguageCode)
    {
        if (string.IsNullOrWhiteSpace(requestedLanguageCode) || string.Equals(requestedLanguageCode, SystemDefaultLanguage, StringComparison.OrdinalIgnoreCase))
            return SystemDefaultLanguage;

        var code = requestedLanguageCode.Trim();
        if (code.Length >= 2)
            code = code[..2].ToLowerInvariant();

        return Localized.ContainsKey(code) ? code : SystemDefaultLanguage;
    }

    private static string ResolveEffectiveLanguageCode(CultureInfo culture)
    {
        var code = culture.TwoLetterISOLanguageName.ToLowerInvariant();
        return Localized.ContainsKey(code) ? code : "en";
    }
}

internal sealed record LanguageChoice(string Code, string DisplayName)
{
    public override string ToString() => DisplayName;
}

internal sealed record ComboBoxChoice<T>(T Value, string DisplayName)
{
    public override string ToString() => DisplayName;
}
